FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y build-essential git && rm -rf /var/lib/apt/lists/*

# copiar requirements y instalar
COPY requirements-docker.txt /app/requirements-docker.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /app/requirements-docker.txt

COPY . /app

EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "3", "src.app:app"]