FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends gcc libpq-dev \
 && pip install --no-cache-dir mlflow boto3 psycopg2-binary \
 && apt-get remove -y gcc \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*

CMD ["sh", "-lc", "mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri postgresql://${MLFLOW_PG_USER:-mlflow}:${MLFLOW_PG_PASSWORD:-mlflowpass}@postgres:5432/${MLFLOW_PG_DB:-mlflow_db} --default-artifact-root s3://mlflow/ --serve-artifacts"]