FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends gcc libpq-dev \
 && pip install --no-cache-dir mlflow boto3 psycopg2-binary \
 && apt-get remove -y gcc \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*

# Default command: escucha en 0.0.0.0 y usa 1 worker para reducir consumo al arrancar
CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5001", \
     "--backend-store-uri", "postgresql://mlflow:mlflowpass@postgres:5432/mlflow_db", \
     "--default-artifact-root", "s3://mlflow", \
     "--serve-artifacts", \
     "--gunicorn-opts", "-w 1 --timeout 120"]